experiment_name: ???
seed: null

use_cuda: True
use_mps: False

log_interval: ???

k_folds: ???

model_type: eo
model_architecture:
  n_in: ???
  n_conjunctions: ???
  num_classes: ???
  weight_init_type: 'normal'

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.00004
scheduler_step: 100
loss_func: ce
batch_size: 32
loader_num_workers: 0
epochs: 200

dds:
  initial_delta: 0.1
  delta_decay_delay: 5
  delta_decay_steps: 1
  delta_decay_rate: 1.1

aux_loss:
  weight_l1_mod_lambda: 1e-3
  tanh_conj_lambda: 1e-1
