experiment_name: bcc_ndnf_std_ip4_nc32_b8_e500
seed: null

use_cuda: True
use_mps: False

log_interval: 100

k_folds: 5
standardise: True

model_type: ndnf
model_architecture:
  invented_predicate_per_input: 4
  n_conjunctions: 32

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.00004
scheduler_step: 100
loss_func: bce
batch_size: 8
loader_num_workers: 0
epochs: 500

dds:
  initial_delta: 0.1
  delta_decay_delay: 5
  delta_decay_steps: 1
  delta_decay_rate: 1.1

aux_loss:
  weight_l1_mod_lambda: 1e-3
  tanh_conj_lambda: 1e-1
  pi_lambda: 1e-3
