experiment_name: bn_fission_mlp_l64_b32_e500
seed: null

use_cuda: True
use_mps: False

log_interval: 20

model_type: mlp
model_architecture:
  num_latent: 64

optimiser: adam
optimiser_lr: 0.003
optimiser_weight_decay: 0.0001
scheduler_step: 50
loss_func: bce
batch_size: 32
loader_num_workers: 4
epochs: 500

aux_loss:
  weight_l1_mod_lambda: 1e-6
