experiment_name: car_ndnf_mt_nc32_b32_dds_monotonic_e500
seed: null

use_cuda: True
use_mps: False

log_interval: 100

val_size: 0.15
val_seed: 73
use_weighted_sampler: False

model_type: mt
model_architecture:
  n_conjunctions: 32

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.0001
scheduler_step: 113
batch_size: 32
loader_num_workers: 0
epochs: 500

dds:
  type: monotonic
  initial_delta: 0.0
  delta_decay_delay: 5
  delta_decay_steps: 3
  delta_decay_rate: 50

aux_loss:
  weight_l1_mod_lambda: 1e-7
  tanh_conj_lambda: 1e-12
  mt_reg_lambda: 1e-3
