experiment_name: car_ndnf_eo_nc32_b64_e500
seed: null

use_cuda: True
use_mps: False

log_interval: 100

val_size: 0.15
use_weighted_sampler: False

model_type: eo
model_architecture:
  n_conjunctions: 32

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.0001
scheduler_step: 113
batch_size: 64
loader_num_workers: 0
epochs: 500

dds:
  initial_delta: 0.1
  delta_decay_delay: 5
  delta_decay_steps: 6
  delta_decay_rate: 1.1

aux_loss:
  weight_l1_mod_lambda: 1e-7
  tanh_conj_lambda: 1e-12
