experiment_name: car_mlp_l64_b64_e300
seed: null

use_cuda: True
use_mps: False

log_interval: 20

val_size: 0.15

model_type: mlp
model_architecture:
  num_latent: 64

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.00004
scheduler_step: 10
batch_size: 64
loader_num_workers: 0
epochs: 300

aux_loss:
  weight_l1_mod_lambda: 1e-3
