experiment_name: covertype_us_mlp_l258x128_b128_e100
seed: null

use_cuda: True
use_mps: False

log_interval: 20

val_size: 0.3
val_seed: 73

model_type: mlp
model_architecture:
  num_latents: [256, 128]

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.00004
scheduler_step: 10
batch_size: 128
loader_num_workers: 0
epochs: 100

aux_loss:
  weight_l1_mod_lambda: 1e-3
