experiment_name: covertype_mlp_l128_b256_e100
seed: null

use_cuda: True
use_mps: False

log_interval: 20

val_size: 0.15

model_type: mlp
model_architecture:
  num_latent: 128

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.00004
scheduler_step: 10
batch_size: 256
loader_num_workers: 0
epochs: 100

aux_loss:
  weight_l1_mod_lambda: 1e-3
