experiment_name: covertype_ndnf_mt_pi16_nc128_b128_e50
seed: null

use_cuda: True
use_mps: False

log_interval: 100

val_size: 0.30
use_weighted_sampler: False

model_type: mt
model_architecture:
  invented_predicate_per_input: 16
  n_conjunctions: 128

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.0001
scheduler_step: 50
batch_size: 128
loader_num_workers: 4
epochs: 50

dds:
  initial_delta: 0.1
  delta_decay_delay: 1
  delta_decay_steps: 1
  delta_decay_rate: 1.1

pi_tau:
  initial_tau: 1
  tau_decay_delay: 10
  tau_decay_steps: 1
  tau_decay_rate: 0.99
  min_tau: 0.1

aux_loss:
  weight_l1_mod_lambda: 1e-7
  tanh_conj_lambda: 1e-12
  pi_lambda: 1e-5
  mt_reg_lambda: 1e-3
