experiment_name: covertype_ndnf_eo_pi16_nc128_b128_e200
seed: null

use_cuda: True
use_mps: False

log_interval: 20

val_size: 0.3
val_seed: 73

use_weighted_sampler: False

model_type: eo
model_architecture:
  invented_predicate_per_input: 16
  n_conjunctions: 128

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.0001
scheduler_step: 50
batch_size: 128
loader_num_workers: 4
epochs: 200

dds:
  initial_delta: 0.1
  delta_decay_delay: 5
  delta_decay_steps: 1
  delta_decay_rate: 1.1

pi_tau:
  initial_tau: 1
  tau_decay_delay: 50
  tau_decay_steps: 1
  tau_decay_rate: 0.99
  min_tau: 0.1

aux_loss:
  weight_l1_mod_lambda: 1e-7
  tanh_conj_lambda: 1e-12
  pi_lambda: 5e-1
