experiment_name: covertype_ndnf_eo_v3_l128x64_b128_e25
seed: null

use_cuda: True
use_mps: False

log_interval: 100

val_size: 0.15
use_weighted_sampler: False

model_type: eo
model_architecture:
  latent_size_list: [128, 64]

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.0001
scheduler_step: 50
batch_size: 128
loader_num_workers: 4
epochs: 25

dds:
  initial_delta: 0.1
  delta_decay_delay: 100
  delta_decay_steps: 10
  delta_decay_rate: 1.1

aux_loss:
  weight_l1_mod_lambda: 1e-7
  tanh_conj_lambda: 1e-12
  pi_lambda: 1e-3
