experiment_name: mushroom_ndnf_nc128_b256_e500
seed: null

use_cuda: True
use_mps: False

log_interval: 100

val_size: 0.15

model_type: ndnf
model_architecture:
  n_conjunctions: 128

optimiser: adam
optimiser_lr: 0.001
optimiser_weight_decay: 0.00004
scheduler_step: 10
loss_func: bce
batch_size: 256
loader_num_workers: 0
epochs: 500

dds:
  initial_delta: 0.1
  delta_decay_delay: 20
  delta_decay_steps: 5
  delta_decay_rate: 1.1

aux_loss:
  weight_l1_mod_lambda: 1e-3
  tanh_conj_lambda: 1e-1
